export const sidebar = {
	default: "var(--sidebar)",
	color: "var(--sidebar-color)",
	"group-title-color": "var(--side-group-title-color)",
	"item-color": "var(--sidebar-item-color)",
	"item-hover": "var(--sidebar-item-hover)",
	"item-active": "var(--sidebar-item-active)",
	"item-active-color": "var(--sidebar-item-active-color)",
	"item-disabled-color": "var(--sidebar-item-disabled-color)",
	"item-icon-color": "var(--sidebar-item-icon-color)",
	"item-icon-active-color": "var(--sidebar-item-icon-active-color)",
	"item-icon-disabled-color": "var(--sidebar-item-icon-disabled-color)",
	"item-expand-color": "var(--sidebar-item-expand-color)",
	"item-children-border": "var(--sidebar-item-children-border)",
	"item-children-indicator": "var(--sidebar-item-children-indicator)",
};
